-- Schema-only extract (NO data) of the ORIGINAL production MariaDB 10.11.19 dump.
-- Generated by tests/Support/extract-production-schema.php from backups/akademija_production.sql
-- (sha256 e8a76c61599ff1f2ceb7baa31269031c98c300603b19e5b6c07d31684d7dbc56).
-- Removed: INSERT statements and AUTO_INCREMENT=<n> counters. Everything else is verbatim.

-- phpMyAdmin SQL Dump
-- version 5.2.3
-- https://www.phpmyadmin.net/
--
-- Host: localhost:3306
-- Generation Time: Sep 28, 2026 at 12:13 PM
-- Server version: 10.11.19-MariaDB
-- PHP Version: 8.4.25

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `auuniblorg_academy`
--

-- --------------------------------------------------------

--
-- Table structure for table `typicms_advertismentboards`
--

CREATE TABLE `typicms_advertismentboards` (
  `id` int(10) UNSIGNED NOT NULL,
  `image_id` int(10) UNSIGNED DEFAULT NULL,
  `title` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`title`)),
  `slug` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`slug`)),
  `summary` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`summary`)),
  `body` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`body`)),
  `category_id` int(10) UNSIGNED DEFAULT NULL,
  `author` varchar(255) DEFAULT NULL,
  `date` datetime DEFAULT NULL,
  `tag` varchar(255) DEFAULT NULL,
  `status` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`status`)),
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `typicms_announcements`
--

CREATE TABLE `typicms_announcements` (
  `id` int(10) UNSIGNED NOT NULL,
  `image_id` int(10) UNSIGNED DEFAULT NULL,
  `status` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`status`)),
  `title` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`title`)),
  `slug` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`slug`)),
  `summary` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`summary`)),
  `body` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`body`)),
  `announcement_category_id` int(10) UNSIGNED DEFAULT NULL,
  `program` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`program`)),
  `year` int(10) NOT NULL DEFAULT 1,
  `professor` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `location` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `date` datetime DEFAULT NULL,
  `expiry` datetime DEFAULT NULL,
  `highlight` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`highlight`)),
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `typicms_announcement_categories`
--

CREATE TABLE `typicms_announcement_categories` (
  `id` int(10) UNSIGNED NOT NULL,
  `title` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`title`)),
  `slug` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`slug`)),
  `status` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`status`)),
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `typicms_announcement_departments`
--

CREATE TABLE `typicms_announcement_departments` (
  `id` int(10) UNSIGNED NOT NULL,
  `title` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`title`)),
  `slug` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`slug`)),
  `status` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`status`)),
  `program_id` int(10) NOT NULL DEFAULT 1,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `typicms_banners`
--

CREATE TABLE `typicms_banners` (
  `id` int(10) UNSIGNED NOT NULL,
  `image_id` int(10) UNSIGNED DEFAULT NULL,
  `status` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`status`)),
  `title` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`title`)),
  `slug` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`slug`)),
  `link` varchar(255) NOT NULL,
  `summary` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`summary`)),
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `typicms_biographies`
--

CREATE TABLE `typicms_biographies` (
  `id` int(10) UNSIGNED NOT NULL,
  `image_id` int(10) UNSIGNED DEFAULT NULL,
  `status` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`status`)),
  `department_id` int(10) UNSIGNED DEFAULT NULL,
  `chef_departments` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`chef_departments`)),
  `directory_departments` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`directory_departments`)),
  `name` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`name`)),
  `title` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`title`)),
  `slug` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`slug`)),
  `section` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`section`)),
  `summary` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`summary`)),
  `email` varchar(255) DEFAULT NULL,
  `phone` varchar(255) DEFAULT NULL,
  `external_link` varchar(255) DEFAULT NULL,
  `linkedin` varchar(255) DEFAULT NULL,
  `instagram` varchar(255) DEFAULT NULL,
  `imdb` varchar(255) DEFAULT NULL,
  `awards` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`awards`)),
  `publications` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`publications`)),
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `typicms_blocks`
--

CREATE TABLE `typicms_blocks` (
  `id` int(10) UNSIGNED NOT NULL,
  `name` varchar(255) NOT NULL,
  `status` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`status`)),
  `body` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`body`)),
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `typicms_categories`
--

CREATE TABLE `typicms_categories` (
  `id` int(10) UNSIGNED NOT NULL,
  `image_id` int(10) UNSIGNED DEFAULT NULL,
  `status` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`status`)),
  `title` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`title`)),
  `slug` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`slug`)),
  `summary` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`summary`)),
  `body` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`body`)),
  `connection` int(11) NOT NULL DEFAULT 0,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `typicms_classschedules`
--

CREATE TABLE `typicms_classschedules` (
  `id` int(10) UNSIGNED NOT NULL,
  `image_id` int(10) UNSIGNED DEFAULT NULL,
  `status` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`status`)),
  `title` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`title`)),
  `slug` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`slug`)),
  `summary` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`summary`)),
  `body` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `announcement_category_id` int(10) UNSIGNED DEFAULT NULL,
  `year` int(10) NOT NULL DEFAULT 1,
  `day_id` int(10) NOT NULL DEFAULT 1,
  `from_date` datetime DEFAULT NULL,
  `to_date` datetime DEFAULT NULL,
  `professor` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `location` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `expiry` datetime DEFAULT NULL,
  `position` int(10) NOT NULL DEFAULT 1,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `announcement_department_id` int(10) UNSIGNED DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `typicms_class_schedule_items`
--

CREATE TABLE `typicms_class_schedule_items` (
  `id` int(10) UNSIGNED NOT NULL,
  `class_schedule_id` int(10) UNSIGNED DEFAULT NULL,
  `title` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `day_id` int(10) NOT NULL DEFAULT 1,
  `type` int(10) NOT NULL DEFAULT 1,
  `from_date` datetime DEFAULT NULL,
  `to_date` datetime DEFAULT NULL,
  `professor` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `location` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `position` int(10) NOT NULL DEFAULT 1,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `typicms_departments`
--

CREATE TABLE `typicms_departments` (
  `id` int(10) UNSIGNED NOT NULL,
  `category_id` int(10) UNSIGNED DEFAULT NULL,
  `status` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`status`)),
  `title` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`title`)),
  `slug` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`slug`)),
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `typicms_files`
--

CREATE TABLE `typicms_files` (
  `id` int(10) UNSIGNED NOT NULL,
  `folder_id` int(10) UNSIGNED DEFAULT NULL,
  `type` enum('a','v','d','i','o','f') DEFAULT NULL,
  `name` varchar(255) DEFAULT NULL,
  `path` varchar(255) DEFAULT NULL,
  `extension` varchar(8) DEFAULT NULL,
  `mimetype` varchar(100) DEFAULT NULL,
  `width` int(10) UNSIGNED DEFAULT NULL,
  `height` int(10) UNSIGNED DEFAULT NULL,
  `filesize` int(10) UNSIGNED DEFAULT NULL,
  `position` int(10) UNSIGNED NOT NULL DEFAULT 0,
  `description` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`description`)),
  `alt_attribute` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`alt_attribute`)),
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `typicms_galleries`
--

CREATE TABLE `typicms_galleries` (
  `id` int(10) UNSIGNED NOT NULL,
  `image_id` int(10) UNSIGNED DEFAULT NULL,
  `title` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`title`)),
  `slug` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`slug`)),
  `summary` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`summary`)),
  `date` datetime NOT NULL,
  `status` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`status`)),
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `typicms_history`
--

CREATE TABLE `typicms_history` (
  `id` bigint(20) UNSIGNED NOT NULL,
  `historable_id` int(10) UNSIGNED NOT NULL,
  `historable_type` varchar(255) NOT NULL,
  `user_id` bigint(20) UNSIGNED DEFAULT NULL,
  `title` varchar(255) DEFAULT NULL,
  `locale` varchar(255) DEFAULT NULL,
  `historable_table` varchar(255) NOT NULL,
  `action` varchar(255) NOT NULL,
  `old` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`old`)),
  `new` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`new`)),
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `typicms_menulinks`
--

CREATE TABLE `typicms_menulinks` (
  `id` int(10) UNSIGNED NOT NULL,
  `menu_id` int(10) UNSIGNED NOT NULL,
  `page_id` int(10) UNSIGNED DEFAULT NULL,
  `section_id` int(10) UNSIGNED DEFAULT NULL,
  `parent_id` int(10) UNSIGNED DEFAULT NULL,
  `image_id` int(10) UNSIGNED DEFAULT NULL,
  `position` int(10) UNSIGNED NOT NULL DEFAULT 0,
  `target` varchar(10) DEFAULT NULL,
  `class` varchar(255) DEFAULT NULL,
  `status` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`status`)),
  `title` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`title`)),
  `url` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`url`)),
  `description` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`description`)),
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `typicms_menus`
--

CREATE TABLE `typicms_menus` (
  `id` int(10) UNSIGNED NOT NULL,
  `image_id` int(10) UNSIGNED DEFAULT NULL,
  `name` varchar(255) NOT NULL,
  `class` varchar(255) DEFAULT NULL,
  `status` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`status`)),
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `typicms_migrations`
--

CREATE TABLE `typicms_migrations` (
  `id` int(10) UNSIGNED NOT NULL,
  `migration` varchar(255) NOT NULL,
  `batch` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `typicms_model_has_files`
--

CREATE TABLE `typicms_model_has_files` (
  `file_id` int(10) UNSIGNED NOT NULL,
  `model_type` varchar(255) NOT NULL,
  `model_id` bigint(20) UNSIGNED NOT NULL,
  `position` int(10) UNSIGNED NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `typicms_news`
--

CREATE TABLE `typicms_news` (
  `id` int(10) UNSIGNED NOT NULL,
  `date` date NOT NULL,
  `image_id` int(10) UNSIGNED DEFAULT NULL,
  `status` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`status`)),
  `highlight` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`highlight`)),
  `title` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`title`)),
  `slug` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`slug`)),
  `summary` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`summary`)),
  `body` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`body`)),
  `category_id` int(10) UNSIGNED DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `typicms_newsletters`
--

CREATE TABLE `typicms_newsletters` (
  `id` int(10) UNSIGNED NOT NULL,
  `email` varchar(255) NOT NULL,
  `name` varchar(255) NOT NULL,
  `type` int(11) NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `typicms_pages`
--

CREATE TABLE `typicms_pages` (
  `id` int(10) UNSIGNED NOT NULL,
  `image_id` int(10) UNSIGNED DEFAULT NULL,
  `position` int(10) UNSIGNED NOT NULL DEFAULT 0,
  `parent_id` int(10) UNSIGNED DEFAULT NULL,
  `private` tinyint(1) NOT NULL DEFAULT 0,
  `is_home` tinyint(1) NOT NULL DEFAULT 0,
  `redirect` tinyint(1) NOT NULL DEFAULT 0,
  `title` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`title`)),
  `slug` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`slug`)),
  `uri` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`uri`)),
  `body` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`body`)),
  `status` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`status`)),
  `meta_keywords` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`meta_keywords`)),
  `meta_description` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`meta_description`)),
  `css` text DEFAULT NULL,
  `js` text DEFAULT NULL,
  `module` varchar(255) DEFAULT NULL,
  `template` varchar(255) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `typicms_page_sections`
--

CREATE TABLE `typicms_page_sections` (
  `id` int(10) UNSIGNED NOT NULL,
  `page_id` int(10) UNSIGNED NOT NULL,
  `image_id` int(10) UNSIGNED DEFAULT NULL,
  `position` int(10) UNSIGNED NOT NULL DEFAULT 0,
  `status` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`status`)),
  `title` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`title`)),
  `slug` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`slug`)),
  `body` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`body`)),
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `typicms_password_resets`
--

CREATE TABLE `typicms_password_resets` (
  `email` varchar(255) NOT NULL,
  `token` varchar(255) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `typicms_permissions`
--

CREATE TABLE `typicms_permissions` (
  `id` bigint(20) UNSIGNED NOT NULL,
  `name` varchar(255) NOT NULL,
  `guard_name` varchar(255) NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `typicms_permission_role`
--

CREATE TABLE `typicms_permission_role` (
  `permission_id` bigint(20) UNSIGNED NOT NULL,
  `role_id` bigint(20) UNSIGNED NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `typicms_permission_user`
--

CREATE TABLE `typicms_permission_user` (
  `permission_id` bigint(20) UNSIGNED NOT NULL,
  `model_type` varchar(255) NOT NULL,
  `model_id` bigint(20) UNSIGNED NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `typicms_roles`
--

CREATE TABLE `typicms_roles` (
  `id` bigint(20) UNSIGNED NOT NULL,
  `name` varchar(255) NOT NULL,
  `guard_name` varchar(255) NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `typicms_role_user`
--

CREATE TABLE `typicms_role_user` (
  `role_id` bigint(20) UNSIGNED NOT NULL,
  `model_type` varchar(255) NOT NULL,
  `model_id` bigint(20) UNSIGNED NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `typicms_settings`
--

CREATE TABLE `typicms_settings` (
  `id` int(10) UNSIGNED NOT NULL,
  `group_name` varchar(255) NOT NULL DEFAULT 'config',
  `key_name` varchar(255) NOT NULL,
  `value` varchar(255) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `typicms_taggables`
--

CREATE TABLE `typicms_taggables` (
  `id` int(10) UNSIGNED NOT NULL,
  `tag_id` int(10) UNSIGNED NOT NULL,
  `taggable_id` int(10) UNSIGNED NOT NULL,
  `taggable_type` varchar(255) NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `typicms_tags`
--

CREATE TABLE `typicms_tags` (
  `id` int(10) UNSIGNED NOT NULL,
  `tag` varchar(255) NOT NULL,
  `slug` varchar(255) NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `typicms_translations`
--

CREATE TABLE `typicms_translations` (
  `id` int(10) UNSIGNED NOT NULL,
  `key` varchar(255) NOT NULL,
  `translation` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`translation`)),
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `typicms_users`
--

CREATE TABLE `typicms_users` (
  `id` bigint(20) UNSIGNED NOT NULL,
  `email` varchar(255) NOT NULL,
  `password` varchar(255) NOT NULL,
  `activated` tinyint(1) NOT NULL DEFAULT 0,
  `superuser` tinyint(1) NOT NULL DEFAULT 0,
  `privacy_policy_accepted` tinyint(1) NOT NULL DEFAULT 0,
  `first_name` varchar(255) DEFAULT NULL,
  `last_name` varchar(255) DEFAULT NULL,
  `phone` varchar(255) DEFAULT NULL,
  `locale` varchar(255) DEFAULT NULL,
  `street` varchar(255) DEFAULT NULL,
  `number` varchar(255) DEFAULT NULL,
  `box` varchar(255) DEFAULT NULL,
  `postal_code` varchar(255) DEFAULT NULL,
  `city` varchar(255) DEFAULT NULL,
  `country` varchar(255) DEFAULT NULL,
  `preferences` text DEFAULT NULL,
  `api_token` char(36) NOT NULL,
  `email_verified_at` timestamp NULL DEFAULT NULL,
  `remember_token` varchar(100) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

--
-- Indexes for dumped tables
--

--
-- Indexes for table `typicms_advertismentboards`
--
ALTER TABLE `typicms_advertismentboards`
  ADD PRIMARY KEY (`id`),
  ADD KEY `typicms_advertismentboards_category_id_foreign` (`category_id`);

--
-- Indexes for table `typicms_announcements`
--
ALTER TABLE `typicms_announcements`
  ADD PRIMARY KEY (`id`),
  ADD KEY `typicms_announcements_announcement_category_id_foreign` (`announcement_category_id`);

--
-- Indexes for table `typicms_announcement_categories`
--
ALTER TABLE `typicms_announcement_categories`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `typicms_announcement_departments`
--
ALTER TABLE `typicms_announcement_departments`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `typicms_banners`
--
ALTER TABLE `typicms_banners`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `typicms_biographies`
--
ALTER TABLE `typicms_biographies`
  ADD PRIMARY KEY (`id`),
  ADD KEY `typicms_biographies_department_id_foreign` (`department_id`);

--
-- Indexes for table `typicms_blocks`
--
ALTER TABLE `typicms_blocks`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `typicms_categories`
--
ALTER TABLE `typicms_categories`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `typicms_classschedules`
--
ALTER TABLE `typicms_classschedules`
  ADD PRIMARY KEY (`id`),
  ADD KEY `typicms_classschedules_announcement_category_id_foreign` (`announcement_category_id`),
  ADD KEY `typicms_classschedules_announcement_department_id_foreign` (`announcement_department_id`);

--
-- Indexes for table `typicms_class_schedule_items`
--
ALTER TABLE `typicms_class_schedule_items`
  ADD PRIMARY KEY (`id`),
  ADD KEY `typicms_class_schedule_items_class_schedule_id_foreign` (`class_schedule_id`);

--
-- Indexes for table `typicms_departments`
--
ALTER TABLE `typicms_departments`
  ADD PRIMARY KEY (`id`),
  ADD KEY `typicms_departments_category_id_foreign` (`category_id`);

--
-- Indexes for table `typicms_files`
--
ALTER TABLE `typicms_files`
  ADD PRIMARY KEY (`id`),
  ADD KEY `typicms_files_folder_id_foreign` (`folder_id`);

--
-- Indexes for table `typicms_galleries`
--
ALTER TABLE `typicms_galleries`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `typicms_history`
--
ALTER TABLE `typicms_history`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `typicms_menulinks`
--
ALTER TABLE `typicms_menulinks`
  ADD PRIMARY KEY (`id`),
  ADD KEY `typicms_menulinks_menu_id_foreign` (`menu_id`),
  ADD KEY `typicms_menulinks_parent_id_foreign` (`parent_id`);

--
-- Indexes for table `typicms_menus`
--
ALTER TABLE `typicms_menus`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `typicms_migrations`
--
ALTER TABLE `typicms_migrations`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `typicms_model_has_files`
--
ALTER TABLE `typicms_model_has_files`
  ADD PRIMARY KEY (`file_id`,`model_id`,`model_type`),
  ADD KEY `file` (`model_type`,`model_id`);

--
-- Indexes for table `typicms_news`
--
ALTER TABLE `typicms_news`
  ADD PRIMARY KEY (`id`),
  ADD KEY `typicms_news_category_id_foreign` (`category_id`);

--
-- Indexes for table `typicms_newsletters`
--
ALTER TABLE `typicms_newsletters`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `typicms_pages`
--
ALTER TABLE `typicms_pages`
  ADD PRIMARY KEY (`id`),
  ADD KEY `typicms_pages_parent_id_foreign` (`parent_id`);

--
-- Indexes for table `typicms_page_sections`
--
ALTER TABLE `typicms_page_sections`
  ADD PRIMARY KEY (`id`),
  ADD KEY `typicms_page_sections_page_id_foreign` (`page_id`);

--
-- Indexes for table `typicms_password_resets`
--
ALTER TABLE `typicms_password_resets`
  ADD KEY `typicms_password_resets_email_index` (`email`),
  ADD KEY `typicms_password_resets_token_index` (`token`);

--
-- Indexes for table `typicms_permissions`
--
ALTER TABLE `typicms_permissions`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `typicms_permission_role`
--
ALTER TABLE `typicms_permission_role`
  ADD PRIMARY KEY (`permission_id`,`role_id`),
  ADD KEY `typicms_permission_role_role_id_foreign` (`role_id`);

--
-- Indexes for table `typicms_permission_user`
--
ALTER TABLE `typicms_permission_user`
  ADD PRIMARY KEY (`permission_id`,`model_id`,`model_type`),
  ADD KEY `model_has_permissions_model_id_model_type_index` (`model_id`,`model_type`);

--
-- Indexes for table `typicms_roles`
--
ALTER TABLE `typicms_roles`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `typicms_role_user`
--
ALTER TABLE `typicms_role_user`
  ADD PRIMARY KEY (`role_id`,`model_id`,`model_type`),
  ADD KEY `model_has_roles_model_id_model_type_index` (`model_id`,`model_type`);

--
-- Indexes for table `typicms_settings`
--
ALTER TABLE `typicms_settings`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `typicms_taggables`
--
ALTER TABLE `typicms_taggables`
  ADD PRIMARY KEY (`id`),
  ADD KEY `typicms_taggables_tag_id_foreign` (`tag_id`);

--
-- Indexes for table `typicms_tags`
--
ALTER TABLE `typicms_tags`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `typicms_translations`
--
ALTER TABLE `typicms_translations`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `typicms_users`
--
ALTER TABLE `typicms_users`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `typicms_users_email_unique` (`email`),
  ADD UNIQUE KEY `typicms_users_api_token_unique` (`api_token`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `typicms_advertismentboards`
--
ALTER TABLE `typicms_advertismentboards`
  MODIFY `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT for table `typicms_announcements`
--
ALTER TABLE `typicms_announcements`
  MODIFY `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT for table `typicms_announcement_categories`
--
ALTER TABLE `typicms_announcement_categories`
  MODIFY `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT for table `typicms_announcement_departments`
--
ALTER TABLE `typicms_announcement_departments`
  MODIFY `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT for table `typicms_banners`
--
ALTER TABLE `typicms_banners`
  MODIFY `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT for table `typicms_biographies`
--
ALTER TABLE `typicms_biographies`
  MODIFY `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT for table `typicms_blocks`
--
ALTER TABLE `typicms_blocks`
  MODIFY `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT for table `typicms_categories`
--
ALTER TABLE `typicms_categories`
  MODIFY `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT for table `typicms_classschedules`
--
ALTER TABLE `typicms_classschedules`
  MODIFY `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT for table `typicms_class_schedule_items`
--
ALTER TABLE `typicms_class_schedule_items`
  MODIFY `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT for table `typicms_departments`
--
ALTER TABLE `typicms_departments`
  MODIFY `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT for table `typicms_files`
--
ALTER TABLE `typicms_files`
  MODIFY `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT for table `typicms_galleries`
--
ALTER TABLE `typicms_galleries`
  MODIFY `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT for table `typicms_history`
--
ALTER TABLE `typicms_history`
  MODIFY `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT for table `typicms_menulinks`
--
ALTER TABLE `typicms_menulinks`
  MODIFY `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT for table `typicms_menus`
--
ALTER TABLE `typicms_menus`
  MODIFY `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT for table `typicms_migrations`
--
ALTER TABLE `typicms_migrations`
  MODIFY `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT for table `typicms_news`
--
ALTER TABLE `typicms_news`
  MODIFY `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT for table `typicms_newsletters`
--
ALTER TABLE `typicms_newsletters`
  MODIFY `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT for table `typicms_pages`
--
ALTER TABLE `typicms_pages`
  MODIFY `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT for table `typicms_page_sections`
--
ALTER TABLE `typicms_page_sections`
  MODIFY `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT for table `typicms_permissions`
--
ALTER TABLE `typicms_permissions`
  MODIFY `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT for table `typicms_roles`
--
ALTER TABLE `typicms_roles`
  MODIFY `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT for table `typicms_settings`
--
ALTER TABLE `typicms_settings`
  MODIFY `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT for table `typicms_taggables`
--
ALTER TABLE `typicms_taggables`
  MODIFY `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT for table `typicms_tags`
--
ALTER TABLE `typicms_tags`
  MODIFY `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT for table `typicms_translations`
--
ALTER TABLE `typicms_translations`
  MODIFY `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT for table `typicms_users`
--
ALTER TABLE `typicms_users`
  MODIFY `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT;

--
-- Constraints for dumped tables
--

--
-- Constraints for table `typicms_advertismentboards`
--
ALTER TABLE `typicms_advertismentboards`
  ADD CONSTRAINT `typicms_advertismentboards_category_id_foreign` FOREIGN KEY (`category_id`) REFERENCES `typicms_categories` (`id`) ON DELETE CASCADE;

--
-- Constraints for table `typicms_announcements`
--
ALTER TABLE `typicms_announcements`
  ADD CONSTRAINT `typicms_announcements_announcement_category_id_foreign` FOREIGN KEY (`announcement_category_id`) REFERENCES `typicms_announcement_categories` (`id`) ON DELETE CASCADE;

--
-- Constraints for table `typicms_biographies`
--
ALTER TABLE `typicms_biographies`
  ADD CONSTRAINT `typicms_biographies_department_id_foreign` FOREIGN KEY (`department_id`) REFERENCES `typicms_departments` (`id`) ON DELETE CASCADE;

--
-- Constraints for table `typicms_classschedules`
--
ALTER TABLE `typicms_classschedules`
  ADD CONSTRAINT `typicms_classschedules_announcement_category_id_foreign` FOREIGN KEY (`announcement_category_id`) REFERENCES `typicms_announcement_categories` (`id`) ON DELETE CASCADE,
  ADD CONSTRAINT `typicms_classschedules_announcement_department_id_foreign` FOREIGN KEY (`announcement_department_id`) REFERENCES `typicms_announcement_departments` (`id`) ON DELETE CASCADE;

--
-- Constraints for table `typicms_class_schedule_items`
--
ALTER TABLE `typicms_class_schedule_items`
  ADD CONSTRAINT `typicms_class_schedule_items_class_schedule_id_foreign` FOREIGN KEY (`class_schedule_id`) REFERENCES `typicms_classschedules` (`id`) ON DELETE CASCADE;

--
-- Constraints for table `typicms_departments`
--
ALTER TABLE `typicms_departments`
  ADD CONSTRAINT `typicms_departments_category_id_foreign` FOREIGN KEY (`category_id`) REFERENCES `typicms_categories` (`id`) ON DELETE CASCADE;

--
-- Constraints for table `typicms_files`
--
ALTER TABLE `typicms_files`
  ADD CONSTRAINT `typicms_files_folder_id_foreign` FOREIGN KEY (`folder_id`) REFERENCES `typicms_files` (`id`);

--
-- Constraints for table `typicms_menulinks`
--
ALTER TABLE `typicms_menulinks`
  ADD CONSTRAINT `typicms_menulinks_menu_id_foreign` FOREIGN KEY (`menu_id`) REFERENCES `typicms_menus` (`id`) ON DELETE CASCADE,
  ADD CONSTRAINT `typicms_menulinks_parent_id_foreign` FOREIGN KEY (`parent_id`) REFERENCES `typicms_menulinks` (`id`) ON DELETE CASCADE;

--
-- Constraints for table `typicms_model_has_files`
--
ALTER TABLE `typicms_model_has_files`
  ADD CONSTRAINT `typicms_model_has_files_file_id_foreign` FOREIGN KEY (`file_id`) REFERENCES `typicms_files` (`id`) ON DELETE CASCADE;

--
-- Constraints for table `typicms_news`
--
ALTER TABLE `typicms_news`
  ADD CONSTRAINT `typicms_news_category_id_foreign` FOREIGN KEY (`category_id`) REFERENCES `typicms_categories` (`id`) ON DELETE CASCADE;

--
-- Constraints for table `typicms_pages`
--
ALTER TABLE `typicms_pages`
  ADD CONSTRAINT `typicms_pages_parent_id_foreign` FOREIGN KEY (`parent_id`) REFERENCES `typicms_pages` (`id`) ON DELETE CASCADE;

--
-- Constraints for table `typicms_page_sections`
--
ALTER TABLE `typicms_page_sections`
  ADD CONSTRAINT `typicms_page_sections_page_id_foreign` FOREIGN KEY (`page_id`) REFERENCES `typicms_pages` (`id`) ON DELETE CASCADE;

--
-- Constraints for table `typicms_permission_role`
--
ALTER TABLE `typicms_permission_role`
  ADD CONSTRAINT `typicms_permission_role_permission_id_foreign` FOREIGN KEY (`permission_id`) REFERENCES `typicms_permissions` (`id`) ON DELETE CASCADE,
  ADD CONSTRAINT `typicms_permission_role_role_id_foreign` FOREIGN KEY (`role_id`) REFERENCES `typicms_roles` (`id`) ON DELETE CASCADE;

--
-- Constraints for table `typicms_permission_user`
--
ALTER TABLE `typicms_permission_user`
  ADD CONSTRAINT `typicms_permission_user_permission_id_foreign` FOREIGN KEY (`permission_id`) REFERENCES `typicms_permissions` (`id`) ON DELETE CASCADE;

--
-- Constraints for table `typicms_role_user`
--
ALTER TABLE `typicms_role_user`
  ADD CONSTRAINT `typicms_role_user_role_id_foreign` FOREIGN KEY (`role_id`) REFERENCES `typicms_roles` (`id`) ON DELETE CASCADE;

--
-- Constraints for table `typicms_taggables`
--
ALTER TABLE `typicms_taggables`
  ADD CONSTRAINT `typicms_taggables_tag_id_foreign` FOREIGN KEY (`tag_id`) REFERENCES `typicms_tags` (`id`) ON DELETE CASCADE;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
