<?php

/*
|--------------------------------------------------------------------------
| Extract a schema-only SQL file from the production database dump
|--------------------------------------------------------------------------
|
| Usage: php tests/Support/extract-production-schema.php \
|            backups/akademija_production.sql \
|            tests/Fixtures/schema/akademija_schema.sql
|
| The input is the original production MariaDB dump (phpMyAdmin format,
| schema + data). The output contains every statement of the dump EXCEPT:
|   - INSERT statements (production data is never copied into tests)
|   - AUTO_INCREMENT=<n> counters (they reveal production row counts)
| Everything else (CREATE TABLE, keys, indexes, foreign keys, CHECK
| constraints, SET/transaction statements) is kept byte-for-byte.
|
| Statements are split on ";" outside of quoted strings/identifiers and
| comments, so data containing ";" or newlines cannot break the split.
|
*/

if ($argc !== 3) {
    fwrite(STDERR, "Usage: php {$argv[0]} <production-dump.sql> <schema-output.sql>\n");
    exit(1);
}

[, $inputPath, $outputPath] = $argv;

$sql = file_get_contents($inputPath);
if ($sql === false) {
    fwrite(STDERR, "Cannot read {$inputPath}\n");
    exit(1);
}

$length = strlen($sql);
$statements = [];
$start = 0;
$i = 0;

while ($i < $length) {
    // Jump to the next character that can change the parser state.
    $i += strcspn($sql, "'\"`;-/#", $i);
    if ($i >= $length) {
        break;
    }
    $char = $sql[$i];

    if ($char === "'" || $char === '"' || $char === '`') {
        // Quoted string/identifier: backslash escapes and doubled quotes.
        $i++;
        while ($i < $length) {
            $i += strcspn($sql, $char.'\\', $i);
            if ($i >= $length) {
                break;
            }
            if ($sql[$i] === '\\' && $char !== '`') {
                $i += 2;
                continue;
            }
            if ($i + 1 < $length && $sql[$i + 1] === $char) {
                $i += 2;
                continue;
            }
            $i++;
            break;
        }
    } elseif (($char === '-' && substr($sql, $i, 2) === '--' && ($i + 2 >= $length || ctype_space($sql[$i + 2]))) || $char === '#') {
        $end = strpos($sql, "\n", $i);
        $i = $end === false ? $length : $end + 1;
    } elseif ($char === '/' && substr($sql, $i, 2) === '/*') {
        $end = strpos($sql, '*/', $i + 2);
        $i = $end === false ? $length : $end + 2;
    } elseif ($char === ';') {
        $statements[] = substr($sql, $start, $i + 1 - $start);
        $start = $i + 1;
        $i++;
    } else {
        $i++;
    }
}
$tail = substr($sql, $start);

$kept = [];
$dropped = 0;
foreach ($statements as $statement) {
    // Strip leading whitespace and "-- " comment lines to see the statement keyword.
    $code = ltrim(preg_replace('/\A(\s*--[^\n]*\n)*/', '', $statement));
    if (stripos($code, 'INSERT INTO') === 0) {
        $dropped++;
        continue;
    }
    $kept[] = preg_replace('/,\s*AUTO_INCREMENT=\d+/', '', $statement);
}

$header = "-- Schema-only extract (NO data) of the ORIGINAL production MariaDB 10.11.19 dump.\n"
    ."-- Generated by tests/Support/extract-production-schema.php from backups/akademija_production.sql\n"
    .'-- (sha256 '.hash_file('sha256', $inputPath).").\n"
    ."-- Removed: INSERT statements and AUTO_INCREMENT=<n> counters. Everything else is verbatim.\n\n";

file_put_contents($outputPath, $header.implode('', $kept).$tail);

fwrite(STDOUT, sprintf(
    "Statements: %d total, %d INSERT dropped, %d kept. Written to %s\n",
    count($statements),
    $dropped,
    count($kept),
    $outputPath
));
